### ISSUE TITLE
ReSwift 4.0 compatibility

### ISSUE THREAD

**Issue by robert-cronin** [mikecole20/ReSwiftThunk#5] opened 2018-09-14 04:33 UTC
Is there any plan to upgrade to be compatible with ReSwift 4.0?

**Comment by mikecole20** [comment] 2018-09-17 21:07
@robert-cronin, not sure how soon I'll have time to do this. But if you are up for opening a PR with the changes, I'm happy to review and merge.

**Comment by robert-cronin** [comment] 2018-09-18 04:58
This would be great for our app, so I'll see what I can do in the next week or so

**Comment by robert-cronin** [comment] 2018-09-19 05:46
Is the ReSwift 4.0 branch an attempt at this already? I noticed there is already a lot of work along these lines in this branch.

**Comment by mikecole20** [comment] 2018-09-19 16:30
Oh yeah! Someone made a pull request for support a while back that I merged. Can you give that a try? Let me know if that works for you, and I'll just merge that over to master and update.

**Comment by mikecole20** [comment] 2018-09-26 06:37
@robert-cronin any luck?

**Comment by ranhsd** [comment] 2018-10-30 19:48
Hi @robert-cronin and @mikecole20 the branch of 4.0 is find and works but the problem is that your PromiseKit example is not working because in the latest Thunk version it returns Void and not Any so you cannot return the promise result from the action creator and then you cannot really handle side effects inside the view layer.  It is possible to change the example with PromiseKit to fit to the new branch? Also, PromiseKit 6 changed a bit since the last time you created this repo.

**Comment by mikecole20** [comment] 2018-11-18 21:41
@ranhsd, thanks for confirming and also for flagging the issue with PromiseKit. I've updated the library to officially point to ReSwift 4.0 and released a new version. I'll take a look into PromiseKit soon and try to get the example updated.

**Comment by ranhsd** [comment] 2018-11-19 09:03
Hi @mikecole20 did you had the chance to look on this one: 

https://github.com/ReSwift/ReSwift-Thunk

**Comment by mikecole20** [comment] 2018-11-28 16:29
#7 is addressing ReSwift's official support. I'm going to go ahead and close this issue out.

**Closed as completed by mikecole20** 2018-11-28 16:29 UTC
